# Generated by Django 5.0.4 on 2024-05-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautystore_app', '0002_alter_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='seller_message',
            field=models.TextField(blank=True),
        ),
    ]
